/**
 * Configuration pour la génération de site statique
 * Utilisé par la commande Artisan: php artisan static:generate
 */

module.exports = {
  // Routes publiques à générer en priorité
  publicRoutes: [
    '/',
    '/projects',
    '/about',
    '/skills',
    '/contact',
    '/blog',
  ],

  // Exclure ces routes de la génération statique
  excludeRoutes: [
    '/dashboard',
    '/profile',
    '/admin',
    '/api',
    '/_debug',
    '/cv',
  ],

  // Configuration de la base URL pour GitHub Pages
  github: {
    // Remplacer par votre URL de base GitHub Pages
    // Format: https://username.github.io/repository
    baseUrl: process.env.GITHUB_PAGES_URL || '',
  },

  // Dossier de sortie
  outputDir: process.env.STATIC_OUTPUT_DIR || 'dist',

  // Port du serveur Laravel pour la génération
  laravelServerPort: 8000,
  laravelServerHost: 'localhost',

  // Assets à copier
  assets: [
    { from: 'public/build', to: 'build' },
    { from: 'public/images', to: 'images' },
    { from: 'public/robots.txt', to: 'robots.txt' },
  ],

  // Fichiers à créer pour GitHub Pages
  createFiles: {
    '.nojekyll': '', // Désactiver Jekyll processing
    '_config.yml': `# GitHub Pages Jekyll configuration
title: Portfolio
description: |
  Static Portfolio Site
  Generated by Laravel & Vite
markdown: kramdown
highlighter: rouge
`,
  },
};
